name: Add chart 4 final
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo workflow-ok
